### ISSUE TITLE
Getting "Cannot read properties of undefined (reading '0')"  on analytics-plugin-aws-pinpoint

### ISSUE THREAD

**Issue by bannarisoftwares** [DavidWells/analytics#372]
Getting following exception even after configuring AWS credentials for "analytics-plugin-aws-pinpoint".

`error - unhandledRejection: TypeError: Cannot read properties of undefined (reading '0')
    at _callee$ (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:1795:52)
    at tryCatch (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:121:40)
    at Generator.invoke [as _invoke] (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:350:22)
    at Generator.prototype.<computed> [as next] (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:173:21)
    at asyncGeneratorStep (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:812:24)
    at _next (/Users/natheeeshkumar/Desktop/Dculus/viewer.forms.dculus.ui/node_modules/@analytics/aws-pinpoint/lib/analytics-plugin-aws-pinpoint.cjs.js:834:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by bannarisoftwares** [comment]
Fixed as part of this PR, Please take a look.

https://github.com/DavidWells/analytics/pull/392/commits/b4fd8335366203795da2fb3e2b8bde992a195835

**Comment by DavidWells** [comment]
Hey thanks for the PR

Released with `@analytics/aws-pinpoint@0.7.10`

Let me know if you still have issues
